#!/usr/bin/env bun

import { app, $ } from "@gutenye/script.js";

app.cmd("build", "Build the project").add(async () => {
  await $`
    rm -rf build
    bun run tsc --project tsconfig.build.json
    bun run tsc-alias --project tsconfig.build.json
  `;
});
